// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// zip_le
IntegerVector zip_le(SEXP sortx, SEXP looky);
RcppExport SEXP zipper_zip_le(SEXP sortxSEXP, SEXP lookySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sortx(sortxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type looky(lookySEXP);
    rcpp_result_gen = Rcpp::wrap(zip_le(sortx, looky));
    return rcpp_result_gen;
END_RCPP
}
// zip_lt
IntegerVector zip_lt(SEXP sortx, SEXP looky);
RcppExport SEXP zipper_zip_lt(SEXP sortxSEXP, SEXP lookySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sortx(sortxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type looky(lookySEXP);
    rcpp_result_gen = Rcpp::wrap(zip_lt(sortx, looky));
    return rcpp_result_gen;
END_RCPP
}
